baseURL = "https://corona.gregboggs.com/"
languageCode = "en-us"
title = "Corona Dashboard"
theme = "coder"

languagecode = "en"
defaultcontentlanguage = "en"

canonifyurls = true


[params]
    author = ""
    description = "Covid 19 Tracker"
    info = "Corona Dashboard"
    dateformat = "Jan 2"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []


[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"



[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 5
            url = "https://www.gregboggs.com/contact-me/"
